zuul:
  ignoredServices: '*'
  ignoredHeaders: Authorization
  sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    first:
      path: /route1/**
      url: http://google.com